# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1r5pOkm__HPNHaHmceSYABYjgpu60TsJS
"""

# STEP 1: Install all required packages
!pip install -q gradio langchain langchain-community langchain-groq sentence-transformers faiss-cpu pypdf python-dotenv

print("✅ All packages installed successfully!")

# STEP 2: Upload your company policy PDFs
from google.colab import files
import os

print("📁 Upload your company policy PDF files:")
uploaded = files.upload()

# List uploaded files
pdf_files = list(uploaded.keys())
print(f"✅ Uploaded {len(pdf_files)} files: {pdf_files}")

# STEP 3 ALTERNATIVE: Direct API key input
import os

# PASTE YOUR GROQ API KEY BETWEEN THE QUOTES BELOW:
groq_api_key = "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"

os.environ['GROQ_API_KEY'] = groq_api_key
print("✅ API key set successfully!")

# STEP 4: Complete chatbot code
import gradio as gr
from langchain_community.document_loaders import PyPDFLoader
from langchain.text_splitter import RecursiveCharacterTextSplitter
from langchain_community.embeddings import HuggingFaceEmbeddings
from langchain_community.vectorstores import FAISS
from langchain_groq import ChatGroq
from langchain.chains.question_answering import load_qa_chain
from langchain.prompts import PromptTemplate
import tempfile
import os

class CompanyPoliciesChatbot:
    def __init__(self):
        self.vector_store = None
        self.embeddings = HuggingFaceEmbeddings(
            model_name="sentence-transformers/all-mpnet-base-v2"
        )

    def get_pdf_text(self, pdf_files):
        """Extract text from PDF files"""
        text = ""
        for pdf_file in pdf_files:
            # Save uploaded file temporarily
            with tempfile.NamedTemporaryFile(delete=False, suffix='.pdf') as tmp_file:
                tmp_file.write(pdf_file)
                tmp_file_path = tmp_file.name

            # Load PDF using PyPDFLoader
            loader = PyPDFLoader(tmp_file_path)
            documents = loader.load()

            for doc in documents:
                text += doc.page_content + "\n"

            # Clean up temporary file
            os.unlink(tmp_file_path)

        return text

    def get_text_chunks(self, text):
        """Split text into chunks"""
        text_splitter = RecursiveCharacterTextSplitter(
            chunk_size=1000,
            chunk_overlap=200
        )
        chunks = text_splitter.split_text(text)
        return chunks

    def setup_vector_store(self, text_chunks):
        """Create vector store"""
        self.vector_store = FAISS.from_texts(text_chunks, embedding=self.embeddings)
        return "✅ Documents processed successfully! You can now ask questions."

    def get_conversational_chain(self):
        """Create the QA chain with Groq"""
        prompt_template = """
        You are a helpful assistant that answers questions about company policies based on the provided context.

        Context: {context}

        Question: {question}

        Please provide a detailed answer based only on the context above.
        If the answer cannot be found in the context, say "I cannot find this information in the provided documents."
        Do not make up information.

        Answer:
        """

        model = ChatGroq(
            model="llama-3.1-8b-instant",
            temperature=0.1,
            groq_api_key=os.environ['GROQ_API_KEY']
        )

        prompt = PromptTemplate(
            template=prompt_template,
            input_variables=["context", "question"]
        )
        chain = load_qa_chain(model, chain_type="stuff", prompt=prompt)
        return chain

    def process_question(self, user_question):
        """Process user question and return response"""
        if not self.vector_store:
            return "❌ Please process documents first by uploading PDFs and clicking 'Process Documents'"

        try:
            # Search for relevant documents
            docs = self.vector_store.similarity_search(user_question, k=3)

            # Get response from chain
            chain = self.get_conversational_chain()
            response = chain(
                {"input_documents": docs, "question": user_question},
                return_only_outputs=True
            )

            # Format response with sources
            sources_text = "\n\n📚 **Sources:**\n"
            for i, doc in enumerate(docs, 1):
                source_name = "Uploaded Document"
                content_preview = doc.page_content[:150] + "..." if len(doc.page_content) > 150 else doc.page_content
                sources_text += f"{i}. {content_preview}\n"

            return f"🤖 {response['output_text']}{sources_text}"

        except Exception as e:
            return f"❌ Error: {str(e)}"

# Initialize chatbot
chatbot = CompanyPoliciesChatbot()
print("✅ Chatbot initialized!")

# STEP 5: Process the uploaded PDF files
print("🔄 Processing uploaded PDF files...")

# Convert uploaded files to the format needed
pdf_data = []
for filename in pdf_files:
    with open(filename, 'rb') as f:
        pdf_data.append(f.read())

# Extract text and create vector store
raw_text = chatbot.get_pdf_text(pdf_data)
text_chunks = chatbot.get_text_chunks(raw_text)
result = chatbot.setup_vector_store(text_chunks)

print(result)
print(f"📊 Processed {len(text_chunks)} text chunks from your documents")

# STEP 6: Test the chatbot
test_questions = [
    "What is the vacation policy?",
    "How many sick days do employees get?",
    "What are the remote work rules?"
]

print("🧪 Testing chatbot...")
for question in test_questions:
    print(f"\nQ: {question}")
    response = chatbot.process_question(question)
    print(f"A: {response}")
    print("-" * 50)

# STEP 7: Create Gradio web interface
def create_gradio_interface():
    """Create the Gradio interface"""

    # Store uploaded files
    uploaded_pdfs = []

    def process_uploaded_files(files):
        """Process files uploaded through Gradio"""
        nonlocal uploaded_pdfs
        uploaded_pdfs = files
        if not files:
            return "⚠️ Please upload PDF files first"

        try:
            # Extract text from uploaded files
            pdf_data = []
            for file in files:
                with open(file.name, 'rb') as f:
                    pdf_data.append(f.read())

            raw_text = chatbot.get_pdf_text(pdf_data)
            text_chunks = chatbot.get_text_chunks(raw_text)
            result = chatbot.setup_vector_store(text_chunks)
            return f"✅ {result} Processed {len(text_chunks)} text chunks."

        except Exception as e:
            return f"❌ Error processing files: {str(e)}"

    def chat_response(message, history):
        """Handle chat responses"""
        return chatbot.process_question(message)

    with gr.Blocks(theme=gr.themes.Soft(), title="Company Policies Chatbot") as demo:
        gr.Markdown(
            """
            # 🏢 Company Policies Chatbot

            Upload your company policy PDFs and ask questions!
            """
        )

        with gr.Row():
            with gr.Column(scale=1):
                gr.Markdown("### 📁 Upload Policies")

                file_input = gr.File(
                    label="Upload PDF Files",
                    file_count="multiple",
                    file_types=[".pdf"],
                    height=100
                )

                process_btn = gr.Button("🚀 Process Documents", variant="primary")
                process_status = gr.Textbox(label="Processing Status", interactive=False)

                gr.Markdown("---")
                gr.Markdown("""
                **Example Questions:**
                - What is the vacation policy?
                - How many sick days are allowed?
                - What are the remote work rules?
                - Tell me about the code of conduct
                """)

            with gr.Column(scale=2):
                gr.Markdown("### 💬 Chat Interface")

                chat_interface = gr.ChatInterface(
                    fn=chat_response,
                    title="",
                    description="Ask questions about your company policies...",
                    examples=[
                        "What is the vacation policy?",
                        "How many sick days do employees get?",
                        "What are the remote work requirements?",
                        "Tell me about the IT security policies"
                    ]
                )

        # Event handlers
        process_btn.click(
            fn=process_uploaded_files,
            inputs=file_input,
            outputs=process_status
        )

    return demo

print("✅ Gradio interface created!")

# STEP 8: Launch the chatbot
print("🚀 Launching Company Policies Chatbot...")
print("📢 The public URL will appear below (may take 10-30 seconds)")

demo = create_gradio_interface()
demo.launch(share=True, debug=True)